#############################################################################
# Makefile for building: rates.app/Contents/MacOS/rates
# Generated by qmake (2.01a) (Qt 4.8.7) on: Thu Aug 1 22:29:14 2019
# Project:  rates.pro
# Template: app
# Command: /Users/qiushuang/anaconda/bin/qmake -o Makefile rates.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.14 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -O2 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.14 -std=c++17 -Wall -W $(DEFINES)
INCPATH       = -I../../../../anaconda/mkspecs/macx-g++ -I. -I../../../../anaconda/include/QtCore -I../../../../anaconda/include/QtGui -I../../../../anaconda/include -I. -Isrc -Iinclude
LINK          = g++
LFLAGS        = -headerpad_max_install_names -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.14 -Xlinker -rpath -Xlinker lib
LIBS          = $(SUBLIBS)  -L/Users/qiushuang/anaconda/lib -lQtGui -L/Users/qiushuang/anaconda/lib -Llib -lQtCore -lOpenXLSX -lQuantLib
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /Users/qiushuang/anaconda/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
export MACOSX_DEPLOYMENT_TARGET = 10.4

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/main.cpp \
		src/widgets/dealInfo.cpp \
		src/widgets/fixedLegSpec.cpp \
		src/widgets/floatLegSpec.cpp \
		src/widgets/optionality.cpp \
		src/widgets/modelInfo.cpp \
		src/widgets/mainWindow.cpp \
		src/model/bermudanSwaption.cpp
OBJECTS       = main.o \
		dealInfo.o \
		fixedLegSpec.o \
		floatLegSpec.o \
		optionality.o \
		modelInfo.o \
		mainWindow.o \
		bermudanSwaption.o
DIST          = ../../../../anaconda/mkspecs/common/unix.conf \
		../../../../anaconda/mkspecs/common/mac.conf \
		../../../../anaconda/mkspecs/common/gcc-base.conf \
		../../../../anaconda/mkspecs/common/gcc-base-macx.conf \
		../../../../anaconda/mkspecs/common/g++-base.conf \
		../../../../anaconda/mkspecs/common/g++-macx.conf \
		../../../../anaconda/mkspecs/qconfig.pri \
		../../../../anaconda/mkspecs/modules/qt_webkit_version.pri \
		../../../../anaconda/mkspecs/features/qt_functions.prf \
		../../../../anaconda/mkspecs/features/qt_config.prf \
		../../../../anaconda/mkspecs/features/exclusive_builds.prf \
		../../../../anaconda/mkspecs/features/default_pre.prf \
		../../../../anaconda/mkspecs/features/mac/default_pre.prf \
		../../../../anaconda/mkspecs/features/release.prf \
		../../../../anaconda/mkspecs/features/default_post.prf \
		../../../../anaconda/mkspecs/features/mac/default_post.prf \
		../../../../anaconda/mkspecs/features/mac/x86_64.prf \
		../../../../anaconda/mkspecs/features/mac/objective_c.prf \
		../../../../anaconda/mkspecs/features/shared.prf \
		../../../../anaconda/mkspecs/features/warn_on.prf \
		../../../../anaconda/mkspecs/features/qt.prf \
		../../../../anaconda/mkspecs/features/unix/thread.prf \
		../../../../anaconda/mkspecs/features/moc.prf \
		../../../../anaconda/mkspecs/features/mac/rez.prf \
		../../../../anaconda/mkspecs/features/mac/sdk.prf \
		../../../../anaconda/mkspecs/features/resources.prf \
		../../../../anaconda/mkspecs/features/uic.prf \
		../../../../anaconda/mkspecs/features/yacc.prf \
		../../../../anaconda/mkspecs/features/lex.prf \
		../../../../anaconda/mkspecs/features/include_source_dir.prf \
		rates.pro
QMAKE_TARGET  = rates
DESTDIR       = 
TARGET        = rates.app/Contents/MacOS/rates

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-O2 \
		-arch \
		x86_64 \
		-Xarch_x86_64 \
		-mmacosx-version-min=10.14 \
		-Wall \
		-W


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile rates.app/Contents/PkgInfo rates.app/Contents/Resources/empty.lproj rates.app/Contents/Info.plist $(TARGET)

$(TARGET):  $(OBJECTS)  
	@$(CHK_DIR_EXISTS) rates.app/Contents/MacOS/ || $(MKDIR) rates.app/Contents/MacOS/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: rates.pro  ../../../../anaconda/mkspecs/macx-g++/qmake.conf ../../../../anaconda/mkspecs/common/unix.conf \
		../../../../anaconda/mkspecs/common/mac.conf \
		../../../../anaconda/mkspecs/common/gcc-base.conf \
		../../../../anaconda/mkspecs/common/gcc-base-macx.conf \
		../../../../anaconda/mkspecs/common/g++-base.conf \
		../../../../anaconda/mkspecs/common/g++-macx.conf \
		../../../../anaconda/mkspecs/qconfig.pri \
		../../../../anaconda/mkspecs/modules/qt_webkit_version.pri \
		../../../../anaconda/mkspecs/features/qt_functions.prf \
		../../../../anaconda/mkspecs/features/qt_config.prf \
		../../../../anaconda/mkspecs/features/exclusive_builds.prf \
		../../../../anaconda/mkspecs/features/default_pre.prf \
		../../../../anaconda/mkspecs/features/mac/default_pre.prf \
		../../../../anaconda/mkspecs/features/release.prf \
		../../../../anaconda/mkspecs/features/default_post.prf \
		../../../../anaconda/mkspecs/features/mac/default_post.prf \
		../../../../anaconda/mkspecs/features/mac/x86_64.prf \
		../../../../anaconda/mkspecs/features/mac/objective_c.prf \
		../../../../anaconda/mkspecs/features/shared.prf \
		../../../../anaconda/mkspecs/features/warn_on.prf \
		../../../../anaconda/mkspecs/features/qt.prf \
		../../../../anaconda/mkspecs/features/unix/thread.prf \
		../../../../anaconda/mkspecs/features/moc.prf \
		../../../../anaconda/mkspecs/features/mac/rez.prf \
		../../../../anaconda/mkspecs/features/mac/sdk.prf \
		../../../../anaconda/mkspecs/features/resources.prf \
		../../../../anaconda/mkspecs/features/uic.prf \
		../../../../anaconda/mkspecs/features/yacc.prf \
		../../../../anaconda/mkspecs/features/lex.prf \
		../../../../anaconda/mkspecs/features/include_source_dir.prf \
		/Users/qiushuang/anaconda/lib/libQtGui.prl \
		/Users/qiushuang/anaconda/lib/libQtCore.prl
	$(QMAKE) -o Makefile rates.pro
../../../../anaconda/mkspecs/common/unix.conf:
../../../../anaconda/mkspecs/common/mac.conf:
../../../../anaconda/mkspecs/common/gcc-base.conf:
../../../../anaconda/mkspecs/common/gcc-base-macx.conf:
../../../../anaconda/mkspecs/common/g++-base.conf:
../../../../anaconda/mkspecs/common/g++-macx.conf:
../../../../anaconda/mkspecs/qconfig.pri:
../../../../anaconda/mkspecs/modules/qt_webkit_version.pri:
../../../../anaconda/mkspecs/features/qt_functions.prf:
../../../../anaconda/mkspecs/features/qt_config.prf:
../../../../anaconda/mkspecs/features/exclusive_builds.prf:
../../../../anaconda/mkspecs/features/default_pre.prf:
../../../../anaconda/mkspecs/features/mac/default_pre.prf:
../../../../anaconda/mkspecs/features/release.prf:
../../../../anaconda/mkspecs/features/default_post.prf:
../../../../anaconda/mkspecs/features/mac/default_post.prf:
../../../../anaconda/mkspecs/features/mac/x86_64.prf:
../../../../anaconda/mkspecs/features/mac/objective_c.prf:
../../../../anaconda/mkspecs/features/shared.prf:
../../../../anaconda/mkspecs/features/warn_on.prf:
../../../../anaconda/mkspecs/features/qt.prf:
../../../../anaconda/mkspecs/features/unix/thread.prf:
../../../../anaconda/mkspecs/features/moc.prf:
../../../../anaconda/mkspecs/features/mac/rez.prf:
../../../../anaconda/mkspecs/features/mac/sdk.prf:
../../../../anaconda/mkspecs/features/resources.prf:
../../../../anaconda/mkspecs/features/uic.prf:
../../../../anaconda/mkspecs/features/yacc.prf:
../../../../anaconda/mkspecs/features/lex.prf:
../../../../anaconda/mkspecs/features/include_source_dir.prf:
/Users/qiushuang/anaconda/lib/libQtGui.prl:
/Users/qiushuang/anaconda/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile rates.pro

rates.app/Contents/PkgInfo: 
	@$(CHK_DIR_EXISTS) rates.app/Contents || $(MKDIR) rates.app/Contents 
	@$(DEL_FILE) rates.app/Contents/PkgInfo
	@echo "APPL????" >rates.app/Contents/PkgInfo
rates.app/Contents/Resources/empty.lproj: 
	@$(CHK_DIR_EXISTS) rates.app/Contents/Resources || $(MKDIR) rates.app/Contents/Resources 
	@touch rates.app/Contents/Resources/empty.lproj
	
rates.app/Contents/Info.plist: 
	@$(CHK_DIR_EXISTS) rates.app/Contents || $(MKDIR) rates.app/Contents 
	@$(DEL_FILE) rates.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,rates,g" -e "s,@TYPEINFO@,????,g" ../../../../anaconda/mkspecs/macx-g++/Info.plist.app >rates.app/Contents/Info.plist
dist: 
	@$(CHK_DIR_EXISTS) .tmp/rates1.0.0 || $(MKDIR) .tmp/rates1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/rates1.0.0/ && $(COPY_FILE) --parents src/main.cpp src/widgets/dealInfo.cpp src/widgets/fixedLegSpec.cpp src/widgets/floatLegSpec.cpp src/widgets/optionality.cpp src/widgets/modelInfo.cpp src/widgets/mainWindow.cpp .tmp/rates1.0.0/ && (cd `dirname .tmp/rates1.0.0` && $(TAR) rates1.0.0.tar rates1.0.0 && $(COMPRESS) rates1.0.0.tar) && $(MOVE) `dirname .tmp/rates1.0.0`/rates1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/rates1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) -r rates.app
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

main.o: src/main.cpp src/widgets/mainWindow.h \
		src/widgets/dealInfo.h \
		src/widgets/fixedLegSpec.h \
		src/widgets/floatLegSpec.h \
		src/widgets/optionality.h \
		src/widgets/modelInfo.h \
		src/model/bermudanSwaption.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

dealInfo.o: src/widgets/dealInfo.cpp src/widgets/dealInfo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dealInfo.o src/widgets/dealInfo.cpp

fixedLegSpec.o: src/widgets/fixedLegSpec.cpp src/widgets/fixedLegSpec.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fixedLegSpec.o src/widgets/fixedLegSpec.cpp

floatLegSpec.o: src/widgets/floatLegSpec.cpp src/widgets/floatLegSpec.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o floatLegSpec.o src/widgets/floatLegSpec.cpp

optionality.o: src/widgets/optionality.cpp src/widgets/optionality.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o optionality.o src/widgets/optionality.cpp

modelInfo.o: src/widgets/modelInfo.cpp src/widgets/modelInfo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o modelInfo.o src/widgets/modelInfo.cpp

mainWindow.o: src/widgets/mainWindow.cpp src/widgets/mainWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainWindow.o src/widgets/mainWindow.cpp

bermudanSwaption.o: src/model/bermudanSwaption.cpp src/model/bermudanSwaption.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bermudanSwaption.o src/model/bermudanSwaption.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

